version: "3.8"

services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - ./apps/api/.env
      - ./apps/api/.env.development
    ports:
      - 5432:5432
    volumes:
      - ./db/init-scripts:/docker-entrypoint-initdb.d

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./apps/api/.env
      - ./apps/api/.env.development
    ports:
      - 3000:3000
    volumes:
      - ./apps/api:/usr/src/app
      - /usr/src/app/node_modules
